### ISSUE TITLE
ex_rabbit_pool or ex_rabbitmq_pool?

### ISSUE THREAD

**Issue by donaldducky** [esl/ex_rabbit_pool#22]
Hi,

I was trying this out and noticed that the docs reference `ex_rabbitmq_pool` while the app that gets generated is `ex_rabbit_pool`.

The project name is also `ex_rabbit_pool` and is referenced as such from the blog post (https://www.erlang-solutions.com/blog/ex_rabbit_pool-open-source-amqp-connection-pool.html).

**Comment by sescobb27** [comment]
Hi @donaldducky thank you for point out this, really appreciate it, indeed there is an error in docs.
