### ISSUE TITLE
Different rabbitmq configs for each pool

### ISSUE THREAD

**Issue by jadencodes** [esl/ex_rabbit_pool#32]
Hi there,

Great work on this pooling mechanism for RabbitMQ. For our setup, we would like to each pool to be able to have its own rabbit configuration (ie host/username/password). From what I understand, this setup does not support that and instead requires using the same rabbitmq to be used for each pool. Perhaps I am misreading though. If not, Is this a use case worth handling?

**Comment by sescobb27** [comment]
Hi @jadencodes thanks for your kind words,
As right now we don't support that option but would be nice to have, the problem is as right now we are really busy with some other projects we don't have bandwidth to implement this, we can add this as our next TODO once we have some free time or if you want to take the lead i can point you up to the right directions so you can make this contribution. let me know cc @bryanhuntesl @Ayanda-D

**Comment by jadencodes** [comment]
Hi @sescobb27 ,

Thanks for the quick response! I have implemented a change on my local fork that converts the Supervisor to be a DynamicSupervisor and adds the function `add_pool(rabbit_config, pool_config)` and it _seems_ to be working as I intended. I will have to add `remove_pool` as well as other helpers.

I am still newish to elixir/otp concurrency so I am unsure of potential drawbacks to this solution. This change would fundamentally change how your project was started as you won't be able to pass it in an initial set of pools to `init/1` but perhaps a compromise would be to have a helper function that accepted your current config and just apply the rabbitmq config to every pool?

Let me know your thoughts, happy to continue working on this and make a PR.

**Comment by sescobb27** [comment]
this is our current implementation https://github.com/esl/ex_rabbit_pool/blob/master/lib/pool_supervisor.ex#L17-L26

what about adding the `rabbitmq_config` option to the `connection_pools` and defaulting to a single `rabbitmq_config` that way each pool its going to have a different setup and we don't over-complicate things. something like

```elixir
for pool_config <- Keyword.get(config, :connection_pools, []) do
  # get pool's rabbitmq_config or a global one
  rabbitmq_config = pool_config[:rabbitmq_config] || Keyword.get(config, :rabbitmq_config, [])
  {_, pool_id} = Keyword.fetch!(pool_config, :name)
  # We are using poolboy's pool as a fifo queue so we can distribute the
  # load between workers
  pool_config = Keyword.merge(pool_config, strategy: :fifo)
  :poolboy.child_spec(pool_id, pool_config, rabbitmq_config)
end
```

**Comment by jadencodes** [comment]
I like the idea of adding an "override" config that is optional but otherwise using the default rabbit config. The use case for adding/removing pools is that we are building a amq proxy that has upstreams that can change (we get these events from etcd, but you could get them from anywhere). I want the benefit of long lived connections with the upstream servers with pooled channels, but I won't necassarily know all the upstream rabbitmqs until after it syncs with Etcd, and these can change after initialization. 

In the local for I mentioned, I modified that exact code you supplied to looks like this: 
```elixir
  def init(_config) do
    DynamicSupervisor.init(strategy: :one_for_one, name: ExRabbitPool.DynamicSupervisor)
  end

  def add_pool(rabbitmq_config, pool_config) do
    #keep same logic as before
    {_, pool_id} = Keyword.fetch!(pool_config, :name)
    pool_config = Keyword.merge(pool_config, strategy: :fifo)
    spec = :poolboy.child_spec(pool_id, pool_config, rabbitmq_config)
    DynamicSupervisor.start_child(ExRabbitPool.DynamicSupervisor, spec)
  end
```

Once it is like this, I can add and remove pools on the fly (ie from a etcd watch event, poll, etc...). But unfortunately I can't pass the config to the `init/1` callback because it throws a "can't call self" error. This could be a misunderstanding in that callback though FWIW. 

What do you think of this approach, assuming I modified the `add_pool/2` to your suggested config?

**Comment by sescobb27** [comment]
I understand your requirements, but I don't think this is something we would add as it is out of the scope of this library, your use case is really particular in the sense of the runtime configuration changes which is not a common thing.

**Comment by jadencodes** [comment]
Thanks for all your input @sescobb27. I have made a fork of your project [here](https://github.com/jadencodes/ex_rabbit_pool) that matches the requirements I need. Feel free to bounce ideas off of me in the future!
